const kenyaLocations: { [key: string]: string[] } = {
  "Nairobi": ["Westlands", "Kasarani", "Embakasi", "Starehe", "Langata", "Dagoretti", "Makadara", "Ruaraka"],
  "Kiambu": ["Thika", "Ruiru", "Kiambu Town", "Limuru", "Githunguri", "Lari"],
  "Machakos": ["Machakos Town", "Mwala", "Kangundo", "Matungulu"],
  "Kajiado": ["Kajiado North", "Kajiado Central", "Kajiado South", "Isinya"],
  "Nakuru": ["Nakuru Town", "Naivasha", "Gilgil", "Molo", "Njoro"],
  "Narok": ["Narok North", "Narok South"],
  "Nyandarua": ["Ol Kalou", "Kinangop"],
  "Nyeri": ["Nyeri Town", "Mathira", "Mukurweini"],
  "Kirinyaga": ["Kerugoya", "Mwea"],
  "Murang'a": ["Murang'a Town", "Kangema", "Kigumo"],
  "Embu": ["Embu Town", "Mbeere North", "Mbeere South"],
  "Tharaka Nithi": ["Chuka", "Tharaka South"],
  "Meru": ["Meru Town", "Imenti North", "Imenti South", "Tigania"],
  "Isiolo": ["Isiolo Town"],
  "Marsabit": ["Marsabit Town"],
  "Samburu": ["Samburu Central"],
  "Laikipia": ["Laikipia West", "Laikipia East"],
  "Baringo": ["Baringo Central"],
  "Elgeyo Marakwet": ["Keiyo North"],
  "Nandi": ["Nandi Hills"],
  "Uasin Gishu": ["Eldoret Town", "Turbo", "Soy"],
  "Trans Nzoia": ["Kitale"],
  "West Pokot": ["Kapenguria"],
  "Turkana": ["Lodwar"],
  "Kakamega": ["Kakamega Town"],
  "Vihiga": ["Vihiga Town"],
  "Bungoma": ["Bungoma Town"],
  "Busia": ["Busia Town"],
  "Siaya": ["Siaya Town"],
  "Kisumu": ["Kisumu City"],
  "Homabay": ["Homabay Town"],
  "Migori": ["Migori Town"],
  "Kisii": ["Kisii Town"],
  "Nyamira": ["Nyamira Town"],
  "Kericho": ["Kericho Town"],
  "Bomet": ["Bomet Town"],
  "Mombasa": ["Mombasa Island", "Likoni"],
  "Kwale": ["Kwale Town"],
  "Kilifi": ["Kilifi Town"],
  "Tana River": ["Hola"],
  "Lamu": ["Lamu Town"],
  "Taita Taveta": ["Voi"],
  "Garissa": ["Garissa Town"],
  "Wajir": ["Wajir Town"],
  "Mandera": ["Mandera Town"],
};